version: "3.8"

services:

  traefik:
    image: "traefik:2.4"
    restart: "unless-stopped"
    depends_on:
      - "authelia"
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik:/letsencrypt"

  authelia:
    image: "authelia/authelia:4.29"
    restart: "unless-stopped"
    command: [ "authelia", "--config", "/configro/configuration.yml" ]
    expose:
      - "9091"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./authelia:/configro:ro"
      - "authelia:/config"
    secrets:
      - "authelia_authentication_backend_ldap_password"
      - "authelia_jwt_secret"
      - "authelia_notifier_smtp_password"
      - "authelia_session_secret"
    environment:
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: "/run/secrets/authelia_authentication_backend_ldap_password"
      AUTHELIA_JWT_SECRET_FILE: "/run/secrets/authelia_jwt_secret"
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: "/run/secrets/authelia_notifier_smtp_password"
      AUTHELIA_SESSION_SECRET_FILE: "/run/secrets/authelia_session_secret"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`${AUTHELIA_FQDN}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTHELIA_FQDN}/"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
      - "traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic"
      - "traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"

  home:
    build: "./home"
    restart: "unless-stopped"
    expose:
      - "80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      HOME_FQDN: "${HOME_FQDN}"
      HOME_LINKS: "radarr:sonarr:downloads:transmission:jackett:resilio"
      HOME_LINK_RADARR: "https://${RADARR_FQDN}"
      HOME_LINK_SONARR: "https://${SONARR_FQDN}"
      HOME_LINK_DOWNLOADS: "https://${DOWNLOADS_FQDN}"
      HOME_LINK_TRANSMISSION: "https://${TRANSMISSION_FQDN}"
      HOME_LINK_JACKETT: "https://${JACKETT_FQDN}"
      HOME_LINK_RESILIO: "https://${RESILIO_FQDN}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=Host(`${HOME_FQDN}`)"
      - "traefik.http.routers.home.entrypoints=websecure"
      - "traefik.http.routers.home.tls=true"
      - "traefik.http.routers.home.tls.certresolver=letsencrypt"
      - "traefik.http.routers.home.middlewares=authelia@docker"

  downloads:
    image: "jmlemetayer/abba"
    restart: "unless-stopped"
    expose:
      - "80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${MEDIA_DIR}:/var/www"
    environment:
      THEME: "vapor"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.downloads.rule=Host(`${DOWNLOADS_FQDN}`)"
      - "traefik.http.routers.downloads.entrypoints=websecure"
      - "traefik.http.routers.downloads.tls=true"
      - "traefik.http.routers.downloads.tls.certresolver=letsencrypt"
      - "traefik.http.routers.downloads.middlewares=authelia-basic@docker"

  transmission:
    image: "linuxserver/transmission"
    restart: "unless-stopped"
    expose:
      - "9091"
    ports:
      - "50500:50500"
      - "50500:50500/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./transmission/init:/custom-cont-init.d/01-init:ro"
      - "./transmission/settings.json:/defaults/settings.json:ro"
      - "${MEDIA_DIR}:/downloads"
      - "transmission:/config"
      - "/tmp/transmission:/watch"
    environment:
      PUID: "${MEDIA_UID}"
      PGID: "${MEDIA_GID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`${TRANSMISSION_FQDN}`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.tls.certresolver=letsencrypt"
      - "traefik.http.routers.transmission.middlewares=authelia@docker"

  flaresolverr:
    image: "flaresolverr/flaresolverr"
    restart: "unless-stopped"
    expose:
      - "8191"
    environment:
      LOG_LEVEL: "info"

  jackett:
    image: "linuxserver/jackett"
    restart: "unless-stopped"
    expose:
      - "9117"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "jackett:/config"
    environment:
      PUID: "${MEDIA_UID}"
      PGID: "${MEDIA_GID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`${JACKETT_FQDN}`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jackett.middlewares=authelia@docker"

  radarr:
    image: "linuxserver/radarr"
    restart: "unless-stopped"
    expose:
      - "7878"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./radarr/init:/custom-cont-init.d/01-init:ro"
      - "${MEDIA_DIR}:/downloads"
      - "radarr:/config"
    environment:
      PUID: "${MEDIA_UID}"
      PGID: "${MEDIA_GID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`${RADARR_FQDN}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.radarr.middlewares=authelia@docker"

  sonarr:
    image: "linuxserver/sonarr"
    restart: "unless-stopped"
    expose:
      - "8989"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./sonarr/init:/custom-cont-init.d/01-init:ro"
      - "${MEDIA_DIR}:/downloads"
      - "sonarr:/config"
    environment:
      PUID: "${MEDIA_UID}"
      PGID: "${MEDIA_GID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${SONARR_FQDN}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"

  resilio:
    image: "linuxserver/resilio-sync"
    restart: "unless-stopped"
    expose:
      - "8888"
    ports:
      - "55555:55555"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${MEDIA_DIR}:/downloads"
      - "${MEDIA_DIR}:/sync"
      - "resilio:/config"
    environment:
      PUID: "${MEDIA_UID}"
      PGID: "${MEDIA_GID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resilio.rule=Host(`${RESILIO_FQDN}`)"
      - "traefik.http.routers.resilio.entrypoints=websecure"
      - "traefik.http.routers.resilio.tls=true"
      - "traefik.http.routers.resilio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.resilio.middlewares=authelia@docker"

volumes:
  authelia:
  jackett:
  radarr:
  resilio:
  sonarr:
  traefik:
  transmission:

secrets:
  authelia_authentication_backend_ldap_password:
    file: "./secrets/authelia_authentication_backend_ldap_password"
  authelia_jwt_secret:
    file: "./secrets/authelia_jwt_secret"
  authelia_notifier_smtp_password:
    file: "./secrets/authelia_notifier_smtp_password"
  authelia_session_secret:
    file: "./secrets/authelia_session_secret"
