version: "3.8"

services:

  traefik:
    image: "traefik:2.4"
    restart: "unless-stopped"
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--api=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik:/letsencrypt"

  downloads:
    image: "jmlemetayer/abba"
    restart: "unless-stopped"
    expose:
      - "80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${MEDIA_DIR}:/var/www"
    environment:
      THEME: "litera"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.downloads.rule=Host(`${DOWNLOADS_FQDN}`)"
      - "traefik.http.routers.downloads.entrypoints=websecure"
      - "traefik.http.routers.downloads.tls=true"
      - "traefik.http.routers.downloads.tls.certresolver=letsencrypt"

volumes:
  traefik:
