log:
  level: "info"

authentication_backend:
  refresh_interval: "5m"

  password_reset:
    disable: true

  ldap:
    address: "ldaps://ldap.example.com"

    base_dn: "dc=ldap,dc=example,dc=com"
    user: "uid=root,cn=users,dc=ldap,dc=example,dc=com"

    attributes:
      mail: "mail"
      username: "uid"
      group_name: "cn"

    additional_users_dn: "cn=users"
    users_filter: "(&({username_attribute}={input})(objectClass=person))"

    additional_groups_dn: "cn=groups"
    groups_filter: "(&(member={dn})(objectclass=posixGroup))"

access_control:
  default_policy: "deny"
  rules:
    - domain: "*.example.com"
      subject: "group:administrators"
      policy: "one_factor"

notifier:
  smtp:
    address: "submission://ssl0.ovh.net:587"
    username: "postmaster@example.com"
    sender: "noreply@example.com"

session:
  name: "authelia_session"
  expiration: "1h"
  inactivity: "5m"
  cookies:
    - domain: "example.com"
      authelia_url: "https://authelia.example.com"

storage:
  local:
    path: "/config/db.sqlite3"
